### ISSUE TITLE
Error including "arduino.h"

### ISSUE THREAD

**Issue by noschang** [maisonsmd/msTask#1]
Hi!

First, congratulations for your work!
Your lib is very simple and intuitive to use.

I'm trying to use your lib in my project using PlatformIO.
I've included your lib in ```platformio.ini``` using the directive ```lib_deps = msTask```.

The library is downloaded and installed in the project correctly. But when I include the header for usage ```include <msTask.h>``` the compiler complains that the file ```arduino.h``` can't be found.

```.piolibdeps/msTask_ID5677/src/msTask.h:12:21: fatal error: arduino.h: No such file or directory```

I tried searching PlatformIO for help but had no success.
Any ideas?

**Comment by maisonsmd** [comment]
Hi!
Thank you for your feedback.

The code compiled successfully on my PC (PlatformIO for VS Code), but I think the issue is that somehow I write "arduino.h" with lower case 'a', which caused the issue to your compiler. 

I corrected it to "Arduino.h". Please download new code and check if it works.

**Comment by maisonsmd** [comment]
This issue is closed due to no recent activities
